server:
  port: 8081

dataServer:
  ip: 192.168.159.178
  port: 9090

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2b8
#    username: root
#    password: ws031103
